"""The genealogical model: records, the Document aggregate, and substructures.

Organized by the spec's own division — top-level records (§3.2.2) in
``_records`` and reusable substructure blocks (§3.2.3) in ``_substructures``,
with the aggregate and Record protocol in ``_document``. Value/datatype
objects live in :mod:`gedcom7.types`.
"""

from __future__ import annotations

from ._document import Document, Header, HeaderSource, Record
from ._pointers import VOID, VoidPointer
from ._records import (
    Alias,
    Association,
    ChangeDate,
    CreationDate,
    Family,
    Individual,
    LdsIndividualOrdinance,
    LdsSpouseSealing,
    Multimedia,
    MultimediaLink,
    RecordBase,
    Repository,
    SharedNote,
    Source,
    SourceCitation,
    SourceData,
    SourceDataEvent,
    SourceRepositoryCitation,
    Submitter,
)
from ._substructures import (
    Address,
    Attribute,
    CallNumber,
    Crop,
    Event,
    EventDetail,
    ExtensionStructure,
    File,
    FileTranslation,
    Identifier,
    LdsOrdinanceDetail,
    Map,
    NamePieces,
    NameTranslation,
    NonEvent,
    Note,
    NoteTranslation,
    PersonalName,
    Place,
    PlaceTranslation,
)

__all__ = [
    "VOID",
    "Address",
    "Alias",
    "Association",
    "Attribute",
    "CallNumber",
    "ChangeDate",
    "CreationDate",
    "Crop",
    "Document",
    "Event",
    "EventDetail",
    "ExtensionStructure",
    "Family",
    "File",
    "FileTranslation",
    "Header",
    "HeaderSource",
    "Identifier",
    "Individual",
    "LdsIndividualOrdinance",
    "LdsOrdinanceDetail",
    "LdsSpouseSealing",
    "Map",
    "Multimedia",
    "MultimediaLink",
    "NamePieces",
    "NameTranslation",
    "NonEvent",
    "Note",
    "NoteTranslation",
    "PersonalName",
    "Place",
    "PlaceTranslation",
    "Record",
    "RecordBase",
    "Repository",
    "SharedNote",
    "Source",
    "SourceCitation",
    "SourceData",
    "SourceDataEvent",
    "SourceRepositoryCitation",
    "Submitter",
    "VoidPointer",
]
